### ISSUE TITLE
[Question] How does spectre handle compromised passwords?

### ISSUE THREAD

**Issue by erisdev** [spectre-app/api#1]
More specifically, how would one deal with a situation where, say, clownshoes.website's sloppy opsec results in one of their algorithmically generated passwords making a cameo in a database dump through no fault of their own?

**Comment by erisdev** [comment]
Aha, the readme in this repo covers it. I searched all over the official website and found nothing, but I glossed right over that.

This should probably be mentioned on the website somewhere.

**Comment by lhunath** [comment]
Good point, thanks!
